# golangci-lint configuration for ZERB
# See: https://golangci-lint.run/docs/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck      # Check error handling
    - govet         # Go vet
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Staticcheck
    - unused        # Detect unused code
    - misspell      # Fix common spelling mistakes
    - gocyclo       # Cyclomatic complexity
    - gosec         # Security issues
  
  settings:
    gocyclo:
      min-complexity: 45
    
    gosec:
      excludes:
        - G104  # Unhandled errors (too noisy, errcheck handles this better)
        - G115  # Integer overflow conversion (common in bit operations)
        - G204  # Subprocess with variable (required for tool execution)
        - G301  # Directory permissions (0755 is standard for dirs)
        - G302  # File permissions for executables
        - G304  # File inclusion via variable (needed for dynamic paths)
        - G305  # File traversal in archive extraction (handled by validation)
        - G306  # WriteFile permissions (0644 is standard for files)
        - G602  # Slice index (handled by bounds checking logic)
  
  exclusions:
    presets:
      - std-error-handling
    rules:
      # Tests can have unchecked errors for setup/teardown operations
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
      
      # Integration tests often have complex setup
      - path: integration_test\.go
        linters:
          - gocyclo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
